language: java
jdk:
  - oraclejdk8

services:
  - docker

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn install -DskipTests -Pdefault,docker
  - mvn deploy -DskipTests -Pdocker
  - docker tag marketreaction/crawler:$TRAVIS_BUILD_NUMBER marketreaction/crawler:latest
  - docker push marketreaction/crawler:latest