language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

install:
  - mvn clean compile -DskipTests
  - mvn test
  - mvn install -DskipTests -Pdefault,docker

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - mvn deploy -DskipTests -Pdocker
