language: java
jdk:
  - oraclejdk8
sudo: required

services:
  - docker

install:
  - mvn clean compile -DskipTests
  - mvn test
  - mvn install -DskipTests -Pdefault,docker

after_success:
  - mvn deploy -DskipTests -Pdefault,docker